baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Serg Hugo Site'
theme = "basic"

[params]
  author = "Sergey"
  description = "My portfolio site"

  gh_url = "https://api.github.com/users"
  gh_user = "your-gh-user"