baseURL = 'http://example.org/'
languageCode = 'uk'
title = 'Serg Hugo Site'
theme = "basic"

paginate = 3

[params]
  author = "Sergey"
  description = "My portfolio site"

  gh_url = "https://api.github.com/users"
  gh_user = "your-gh-user"

pygmentsUseClasses = true

[taxonomies]
  year = "year"
  month = "month"
  tag = "tags"
  category = "categories"

[permalinks]
  posts = "posts/:year/:month/:slug/"
